### ISSUE TITLE
Resizing images to be no bigger than 90000 pixels resulting in 0 byte images

### ISSUE THREAD

**Issue by elihid** [armindocachada/tensorflow-custom-classification-art-nativity#2]
```
import os

def resizeImages(sourceFolder, destinationFolder, maxPixels=1048576):
  os.makedirs(destinationFolder, exist_ok=True)
  for path, subdirs, files in os.walk(sourceFolder):
      
      relativeDir=path.replace(sourceFolder, "")
      destinationFolderPath = destinationFolder + relativeDir
      os.makedirs(destinationFolderPath,exist_ok=True)
      for fileName in files:
          if not fileName.endswith(".csv"):
            sourceFilepath=os.path.join(path,fileName)
            destinationFilepath=os.path.join(destinationFolderPath, fileName)
            print(f"sourceFilepath={sourceFilepath} destinationFilepath={destinationFilepath}")
            os.system(f"convert {sourceFilepath} -resize {maxPixels}@\> {destinationFilepath}")
```

I am stuck at this part of the code. I am running this on Windows as suggested here: 
https://spltech.co.uk/how-to-install-tensorflow-2-5-with-cuda-11-2-and-cudnn-8-1-for-windows-10/#respond
`# resize training images
sourceFolder="./dataset"
destinationFolder = "./resized/dataset"
resizeImages(sourceFolder, destinationFolder, maxPixels=90000)`

For some reason the resizing from ImageMagick results in 0 byte images. I am unsure if it is something to do with the code or the way i am trying to execute it. I am using a Jupyter notebook in an Anaconda virtualenv. 
Any help is much appreciated!

**Comment by elihid** [comment]
It seems to be an issue with Windows. In systems command `magick convert` must be used instead of `convert`. Also, from the [ImageMagick documentation](https://legacy.imagemagick.org/Usage/resize/) the only shrink flag is a special character and is treated differently on Windows and Linux bash. 
So: 
` os.system(f"convert {sourceFilepath} -resize {maxPixels}@\> {destinationFilepath}")`
must be replaced with: 
` os.system(f" magick convert {sourceFilepath} -resize {maxPixels}@^> {destinationFilepath}")`
to be properly executed on a Windows system. Closing this issue.

**Comment by armindocachada** [comment]
Thanks for diagnosing!
